### ISSUE TITLE
偶尔会出现卡顿情况，不知道哪里问，用剪映软件剪辑视频有时会很卡，显卡信息里显示不全有影响吗？还有就是显存要不要设置大一点？

### ISSUE THREAD

**Issue by lilongooz** [lxopencv/NUC8-OC#10]
大佬！看到帮忙解答一下，偶尔会出现卡顿情况，不知道哪里问，用剪映软件剪辑视频有时会很卡，显卡信息里显示不全有影响吗？还有就是显存要不要设置大一点？设置大一些会不会不会容易卡顿了？
<img width="773" alt="截屏2024-05-02 17 34 54" src="https://github.com/lxopencv/NUC8-OC/assets/147719076/955d2b82-26c6-45a7-8db3-e26d63f36221">

**Comment by lxopencv** [comment]
655就是一个很小的核显，做不了大剪辑的。定位只是办公处理，看看视频这种。

**Comment by lilongooz** [comment]
> 655就是一个很小的核显，做不了大剪辑的。定位只是办公处理，看看视频这种。

好的谢谢。
