### ISSUE TITLE
系统无痛升级到14.5之后，开机可以正常进入到用户登录界面，但是输入密码点击登录之后，会显示“电脑因为出现问题而重新启动”

### ISSUE THREAD

**Issue by resona** [lxopencv/NUC8-OC#12]
![image](https://github.com/lxopencv/NUC8-OC/assets/21964636/fd42086a-433b-4d83-be49-8e163e514399)

进入到用户登录界面的时候，我注意到右上角的wifi图标显示为灰色，并且点击没有反应，不知道是不是wifi驱动的原因造成的。
不知道大神有没有遇到过这个问题呢？可以给个解决的思路嘛？

谢谢大神了！！

**Comment by resona** [comment]
另外补充一下，我之前使用的是12.5的系统，然后想着直接系统更新到最新的14.5，操作步骤为：
1、替换OC0.9.9-EFI-NUC8-intel-wifi-BT-CardReader-Sonoma-14.4文件
2、OC里面的Misc->Secutity->SecureBootModel设为Disabled
3、系统设置界面检查更新，并且开始自动下载完整系统包并且安装，安装完成之后提示重启系统
4、重启之后，OC界面选择“Install”，开始进行系统安装，安装完成之后，自动重启
5、选择系统盘正常开机进入到系统登录界面（到这一步之前都完全正常）
6、输入登录密码登录，出现上面的“电脑因为出现问题而重新启动”。此时注意到登录界面右上角的wifi图标显示为灰色，并且点击没有反应。
7、系统自动重启，会跳出五国界面，然后继续重启
8、接下来就是重复步骤5了……

**Comment by lxopencv** [comment]
跨大版本建议你直接安装Sonoma然后替换。改动太多了

**Comment by resona** [comment]
好的，十分感谢解答！！
