### ISSUE TITLE
mac OS Ventura 13.6.7可以用么,只是想让雷电3接口工作正常支持热插拔,应该如何替换

### ISSUE THREAD

**Issue by yangmengli** [lxopencv/NUC8-OC#15]
![image](https://github.com/lxopencv/NUC8-OC/assets/6427961/3b00a2c4-5006-4d45-8d73-d27911d9a866)

**Comment by lxopencv** [comment]
不能用于13.6.7。雷电3我这里一直可以支持热插拔。这个和你bios设置还有bios固件都有关系。正常如果从yippeeghost获取版本的都支持。

**Comment by yangmengli** [comment]
![image](https://github.com/lxopencv/NUC8-OC/assets/6427961/48e1d4a1-17da-42bd-b47d-fa0fac47a6ad)![image](https://github.com/lxopencv/NUC8-OC/assets/6427961/cbdab1ed-22b3-42cf-91b5-adf74f6b4b7c)
这是我的BIOS版本和设置,BIOS版本应该是0090
但是远景论坛现在没法注册了尴尬,大佬你知道去哪可以下载么,就你说的这个yippeeghost大神的EFI

**Comment by lxopencv** [comment]
[Uploading NUC8-OC.txt…]()

**Comment by yangmengli** [comment]
感谢大佬
