### ISSUE TITLE
读卡器问题

### ISSUE THREAD

**Issue by Orangemiao** [lxopencv/NUC8-OC#16]
您好，我使用的efi是OC1.0.1-EFI-NUC8-intel-wifi-BT-CardReader-Sonoma-0806.zip，macos版本为14.4.1
具体问题为开机后大概率不能识别不到内存卡(Windows下正常）
![QQ_1723381725225](https://github.com/user-attachments/assets/64813bed-94ed-4f8e-ae31-0946c23a6e10)
系统信息中可以识别到读卡器但是并没有内存卡

**Comment by lxopencv** [comment]
查询下是否是硬改机型，这个是不对的，走的应该是USB拓展，速度X4

**Comment by Orangemiao** [comment]
原装i5bek，并非硬改机型

**Comment by lxopencv** [comment]
你截图的内容是我注入的一个编号，为了能使得再一些软件中让读卡器被标记。实际的读卡器应该是这个。
![image](https://github.com/user-attachments/assets/38ef0048-8dc1-43a7-99c4-4042a0ff2d39)
尝试windows切换到Mac前清理下nvram。如果还存在问题尝试在kernel中启用RealtekCardReaderFriend.kext 。但可能导致[#9]。

**Comment by Orangemiao** [comment]
清除nvram并没有解决，但也只能这样了
