### ISSUE TITLE
全新安装的版本选择问题

### ISSUE THREAD

**Issue by yxnchen** [lxopencv/NUC8-OC#17]
请问一下：

1）如果目前全新安装，应该选择release里面的哪个EFI压缩包？有带14.4，有不带
![image](https://github.com/user-attachments/assets/4b6b2fa2-5651-45e7-9b5c-37a44da304d6)

2）如果目前全新安装，镜像是否需要选择14.4？直接用14.6更换最新的OC来进行安装是否可以？

**Comment by lxopencv** [comment]
https://github.com/lxopencv/NUC8-OC/blob/main/README.md
参考readme说明，文件中不包含任何安装镜像

**Comment by yxnchen** [comment]
先安装的14.4，测试成功
