### ISSUE TITLE
刚试了硬改机型的EFI，无线无法使用。

### ISSUE THREAD

**Issue by Liujishou** [lxopencv/NUC8-OC#2]
无线图标感叹号，无法打开。
使用论坛上的https://bbs.pcbeta.com/viewthread-1982214-1-1.html
再用OpenCore Legacy Patcher打下补丁就能使用
发给你参考下，修改修改硬改的EFI配置文件

**Comment by xn2xx** [comment]
> 无线图标感叹号，无法打开。 使用论坛上的https://bbs.pcbeta.com/viewthread-1982214-1-1.html 再用OpenCore Legacy Patcher打下补丁就能使用 发给你参考下，修改修改硬改的EFI配置文件

您好、请问下怎么打补丁呢，我也是wifi无法驱动。没弄出来。

**Comment by Liujishou** [comment]
> > 无线图标感叹号，无法打开。 使用论坛上的https://bbs.pcbeta.com/viewthread-1982214-1-1.html 再用OpenCore Legacy Patcher打下补丁就能使用 发给你参考下，修改修改硬改的EFI配置文件
> 
> 您好、请问下怎么打补丁呢，我也是wifi无法驱动。没弄出来。

打开论坛上的帖子。里面楼主在评论有说方法。我是用论坛发的efi文件的
OpenCore Legacy Patcher：https://github.com/dortania/Opencore-Legacy-Patcher/

**Comment by Liujishou** [comment]
> 已更新，待测试

刚测试，换了efi后也重置NVRAM 但会卡苹果图标，进不了系统。

**Comment by xn2xx** [comment]
> 已更新，待测试

今天有空又下了新版本测试了一下。换了新的efi进不了系统。

**Comment by lxopencv** [comment]
不再提供硬改版本
