### ISSUE TITLE
小概率会跳过opencore选择器(黑屏), 直接进macos.

### ISSUE THREAD

**Issue by hardy-122** [lxopencv/NUC8-OC#7]
目前是opencore0.99./sonoma14.4, 但是这个问题感觉从前两年的版本就出现了, 尝试过诸多版本efi都会出现.
想问下大佬您遇到过吗?
会不会是是用了hdmi接口的原因? 您的显示器和nuc是用什么接口的呢?

**Comment by lxopencv** [comment]
HDMI接口显示

**Comment by hardy-122** [comment]
> HDMI接口显示

1. 不是通过修改配置就能解决的软件层面问题是吗?
2. "给hdmi插头加个usb转接头" 或者 "换个其它接口的显示器" 才可能解决这个问题是吗 ?

**Comment by hardy-122** [comment]
我打算买个雷电3 接口的拓展坞来转接 hdmi 显示器试试了. 
如果确认问题解决的话我再来反馈.

**Comment by hardy-122** [comment]
> HDMI接口显示

我发现了一个问题，您的config文件引导下，用hackintool - 应用补丁 - 接口页面，检查接口时，通过插拔nuc接的hdmi线，发现0x05的hdmi接口被识别成DP，通过 https://blog.skk.moe/post/hackintosh-fix-magenta-screen/ 这篇教程，我修改成了hdmi。

或许是文章提到的 “ _有时候 HackinTool 修改某些选项时会重置接口设置，所以这时候你应该再切回「接口」，检查一遍接口设置是否正确、必要时进行更正。_”  我检查时才发现刚设置好的hdmi接口，会在第一遍设置完还没生成补丁时自动变回dp，所以需要修改第二遍。或许是 hackintool 这种糟糕的特性造成了这个hdmi接口没被调整。

我不清楚这是不是问题所在，以及是不是其他人是否是用的其它类型接口，但我还是觉得用hdmi接口且遇到问题的可以尝试下这篇教程，尤其是我上一段提到的hackintool会自动修改用户修改好的内容，所以要复查的这一条。

**Comment by lxopencv** [comment]
应该不是这个问题，这个解决的是色彩映射不正确的问题，类似于图像处理中RGB和BGR顺序不同导致的问题。
你所描述的情况更像硬件上的供电（显示器或者HDMI线）问题导致，这个和你确认下，是否连BIOS都跳过显示了。目前我尚未遇到过不显示opencore阶段。但是曾经有用树莓派显示器（5v供电）在nuc8 使用Ubuntu情况下有出现过不显示BIOS阶段直接进系统后才显示，和你描述的相对接近。

**Comment by hardy-122** [comment]
> 应该不是这个问题……
非常感谢, 但还是确认下, 你说的供电问题是 "显示intel Nuc" 和 "OpenCore选择器" 两个界面都不显示是吗?

**Comment by lxopencv** [comment]
> > 应该不是这个问题……
> 
> 非常感谢, 但还是确认下, 你说的供电问题是 《"显示intel Nuc" 和 "OpenCore选择器" 两个界面》都不显示是吗?

是的，在树莓派显示器（5v供电）情况下不会显示

**Comment by hardy-122** [comment]
> 是的，在树莓派显示器（5v供电）情况下不会显示

回想了下, 您的推论应该是对的: 
我开机不显示 "Intel Nuc页面" 和 "OpenCore页面" 高发于我利用插电自动开机时, 这时插板/显示器/电脑同时插电开启, 可能是因此造成的不稳定.

不光是因为高发于刚插电时,  而且我觉得软件层面问题不太会时有时无. 

非常感谢~
