### ISSUE TITLE
nuc8i5bek原版本为14.3.1，更新这个EFI之后无限卡白苹果重启啦。。。。

### ISSUE THREAD

**Issue by Ericanymouse** [lxopencv/NUC8-OC#8]
更新的EFI是0.99升14.4的那个版本，求助～～

**Comment by lxopencv** [comment]
更新方式：替换OC0.9.9-EFI-NUC8-intel-wifi-BT-CardReader-Sonoma-14.4文件，重启后，下载更新安装更新
完整说明：OC里面的Misc->Secutity->SecureBootModel设为Disabled，然后更新，替换新的AirportItlwm

**Comment by Ericanymouse** [comment]
那么，现在无限重启，是因为没有把SecureBootModel设为Disabled么？

**Comment by Ericanymouse** [comment]
好嘞，谢谢。容我搞到硬盘盒之后修改一下试试。

**Comment by Ericanymouse** [comment]
不行哎，这里本来就是disable的。。。是要先吧AirportItlwm这个替换掉什么版本的吗？

**Comment by lxopencv** [comment]
1.替换OC0.9.9-EFI-NUC8-intel-wifi-BT-CardReader-Sonoma-14.4文件，
2.重启后
3.下载更新安装更新
目前卡在第几步？

**Comment by Ericanymouse** [comment]
我用另外一个包里的AirportItlwm替换了这个14.4的包，现在成功进入了系统，Wi-Fi蓝牙也是正常的sonnoma 14.3.1

**Comment by Ericanymouse** [comment]
然后更新系统，重启的时候挂了。再修改efi里面的AirportItlwm，替换成14.4里面的，重启，好了，现在系统是14.4.1啦
